### ISSUE TITLE
1000x.dna can be used in datacenter scenario?

### ISSUE THREAD

**Issue by liujingbbd** [pratiksha/learnability-reproduce#3]
Hi authors of Tao,
I am doing a comparison experiment of congestion control for datacenter-like environment(i.e., high bandwidth and low path delay), so I have a question: 1000x.dna can be used as Remy to test?  
Like test in many connections, and test in competing with Cubic. Did the model be trained in the same or similar scenario that I said ? Or if I want to do comparison, did I must set the same scenaorio that you trained with? 

Thanks for your any response! : )

Jing Liu

**Comment by anirudhSK** [comment]
The 1000x DNA is available here: https://github.com/pratiksha/learnability-reproduce/blob/master/fig2-linkspeed/bigbertha2.dna.5 (the name is a bit confusing). If you want to recreate that DNA file, you can checkout this commit of the remy repository: https://github.com/tcpexmachina/remy/commit/ad05f8a6cbedc4b4c1a74ffbc3640f02e91920d9 Also, we don't check this area frequently. You'll probably get a quicker response if you email remy@mit.edu
